name: "higgsInteractionNet"
platform: "onnxruntime_onnx"
max_batch_size : 500
dynamic_batching {
   preferred_batch_size: [ 200 ]
}
input [
  {
    name: "input_cpf"
    data_type: TYPE_FP32
    dims: [ 30, 60 ]
  },
  {
    name: "input_sv"
    data_type: TYPE_FP32
    dims: [ 14, 5 ]
  }
]
output [
  {
    name: "output1"
    data_type: TYPE_FP32
    dims: [ 2 ]
    label_filename: "higgs_interactionnet_labels.txt"
  }
]
optimization {graph : {level : -1}}
