name: "particlenet_AK4"
platform: "onnxruntime_onnx"
max_batch_size : 500
dynamic_batching {
   preferred_batch_size: [ 200 ]
}
input [
  {
    name: "pf_points"
    data_type: TYPE_FP32
    dims: [ 2, -1 ]
  },
  {
    name: "pf_features"
    data_type: TYPE_FP32
    dims: [ 20, -1 ]
  },
  {
    name: "pf_mask"
    data_type: TYPE_FP32
    dims: [ 1, -1 ]
  },
  {
    name: "sv_points"
    data_type: TYPE_FP32
    dims: [ 2, -1 ]
  },
  {
    name: "sv_features"
    data_type: TYPE_FP32
    dims: [ 11, -1 ]
  },
  {
    name: "sv_mask"
    data_type: TYPE_FP32
    dims: [ 1, -1 ]
  }
]
output [
  {
    name: "softmax"
    data_type: TYPE_FP32
    dims: [ 8 ]
    label_filename: "particlenet_labels.txt"
  }
]
optimization {graph : {level : -1}}
