name: "unifiedparticletransformer_AK4"
platform: "onnxruntime_onnx"
input [
  {
    name: "input_1"
    data_type: TYPE_FP32
    dims: [ -1, -1, 25 ]
  },
  {
    name: "input_2"
    data_type: TYPE_FP32
    dims: [ -1, -1, 18 ]
  },
  {
    name: "input_3"
    data_type: TYPE_FP32
    dims: [ -1, -1, 8 ]
  },
  {
    name: "input_4"
    data_type: TYPE_FP32
    dims: [ -1, -1, 14 ]
  },
  {
    name: "input_5"
    data_type: TYPE_FP32
    dims: [ -1, -1, 4 ]
  },
  {
    name: "input_6"
    data_type: TYPE_FP32
    dims: [ -1, -1, 4 ]
  },
  {
    name: "input_7"
    data_type: TYPE_FP32
    dims: [ -1, -1, 4 ]
  },
  {
    name: "input_8"
    data_type: TYPE_FP32
    dims: [ -1, -1, 4 ]
  }
]
output [
  {
    name: "softmax"
    data_type: TYPE_FP32
    dims: [ -1, 30 ]
    label_filename: "unifiedparticletransformer_labels.txt"
  }
]
optimization {graph : {level : -1}}
