name: "particletransformer_AK4"
platform: "onnxruntime_onnx"
max_batch_size: 500
input {
  name: "input_1"
  data_type: TYPE_FP32
  dims: [-1, 16]
}
input {
  name: "input_2"
  data_type: TYPE_FP32
  dims: [-1, 8]
}
input {
  name: "input_3"
  data_type: TYPE_FP32
  dims: [-1, 14]
}
input {
  name: "input_4"
  data_type: TYPE_FP32
  dims: [-1, 4]
}
input {
  name: "input_5"
  data_type: TYPE_FP32
  dims: [-1, 4]
}
input {
  name: "input_6"
  data_type: TYPE_FP32
  dims: [-1, 4]
}
output {
  name: "softmax"
  data_type: TYPE_FP32
  dims: [6]
  label_filename: "particletransformer_labels.txt"
}
dynamic_batching {
  preferred_batch_size: [200]
}
optimization {
  graph {
    level: -1
  }
}
model_repository_agents {
  agents {
    name: "checksum"
    parameters {
      key: "MD5:1/model.onnx"
      value: "e9ad0c98366e337e2562a9522ffd575b"
    }
  }
}
